# Generated by Django 2.2.5 on 2019-11-15 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='request_category',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Category'),
        ),
        migrations.AddField(
            model_name='request_category',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Request'),
        ),
        migrations.AddField(
            model_name='request',
            name='category',
            field=models.ManyToManyField(through='Inventory.Request_Category', to='Inventory.Category'),
        ),
        migrations.AddField(
            model_name='request',
            name='equipment',
            field=models.ManyToManyField(to='Inventory.Equipment'),
        ),
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='repair',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Equipment'),
        ),
        migrations.AddField(
            model_name='loan',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Equipment'),
        ),
        migrations.AddField(
            model_name='loan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipmentdebt',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Category'),
        ),
        migrations.AddField(
            model_name='equipmentdebt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Category'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='group',
            field=models.ManyToManyField(blank=True, to='Inventory.Group'),
        ),
        migrations.AddField(
            model_name='choices',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Attribute'),
        ),
        migrations.AddField(
            model_name='attribute_equipment',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Attribute'),
        ),
        migrations.AddField(
            model_name='attribute_equipment',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Equipment'),
        ),
        migrations.AddField(
            model_name='attribute_equipment',
            name='value_cho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Inventory.Choices'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.Category'),
        ),
    ]
